### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by LtEntropy** [BahamutDragon/pcgen#1001]
I'm using PCGen v6.09.03, using a cloned repository from GitHub, running Java 8 build 261.

Every time I try to load the data, it always stops at mm_kits, and get a long list of stuff, and the the same problem in the log (this is just the end, what I assume describes the issue):

java.lang.NullPointerException
	at pcgen.cdom.helper.AbilityTargetSelector.getChoiceClass(AbilityTargetSelector.java:199)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:196)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:47)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:270)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:253)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:760)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:489)
	at pcgen.persistence.SourceFileLoader.run(SourceFileLoader.java:241)
	at pcgen.gui2.util.StatusWorker.doInBackground(StatusWorker.java:110)
	at pcgen.gui2.util.StatusWorker.doInBackground(StatusWorker.java:42)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

I get two of these errors each time, while the other one further up says:

java.lang.NullPointerException
	at pcgen.rules.persistence.token.PreCompatibilityToken.parseToken(PreCompatibilityToken.java:63)
	at pcgen.rules.persistence.token.PreCompatibilityToken.parseToken(PreCompatibilityToken.java:34)
	at pcgen.rules.persistence.TokenSupport.processClassTokens(TokenSupport.java:107)
	at pcgen.rules.persistence.TokenSupport.processToken(TokenSupport.java:90)
	at pcgen.rules.context.LoadContextInst.processToken(LoadContextInst.java:330)
	at pcgen.rules.context.RuntimeLoadContext.processToken(RuntimeLoadContext.java:20)
	at pcgen.persistence.lst.LstUtils.processToken(LstUtils.java:139)
	at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:106)
	at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:35)
	at pcgen.persistence.lst.LstObjectFileLoader.loadLstFile(LstObjectFileLoader.java:378)
	at pcgen.persistence.lst.LstObjectFileLoader.loadLstFiles(LstObjectFileLoader.java:90)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:618)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:484)
	at pcgen.persistence.SourceFileLoader.run(SourceFileLoader.java:241)
	at pcgen.gui2.util.StatusWorker.doInBackground(StatusWorker.java:110)
	at pcgen.gui2.util.StatusWorker.doInBackground(StatusWorker.java:42)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by BahamutDragon** [comment]
I believe you need to run java 11+ for 6.09. The PCGen team has the prerequisites listed on their Github releases download for each version.

Good luck!
