### ISSUE TITLE
It's impossible to create a character with 3.5 in Bahamut mode

### ISSUE THREAD

**Issue by tivv** [BahamutDragon/pcgen#1040]
Get a NullPointerException in 6.08.00 RC8 and latest master:
```
23:39:54.248 INFO Thread-2 SourceFileLoader:534 Loading game Bahamut35e and sources [Player's Handbook - Core Rulebook I v.3.5, Dungeon Master's Guide - Core Rulebook II v.3.5, Monster Manual - Core Rulebook III v.3.5, Complete Adventurer, Complete Arcane, Complete Champion, Complete Divine, Complete Mage, Complete Warrior, Magic Item Compendium, Spell Compendium].
23:40:10.235 SEVERE AWT-EventQueue-0 CharacterManager:106 Unable to create character with data DataSet [gameMode=Bahamut35e, campaigns=[Magic Item Compendium, Complete Champion, Complete Mage, Spell Compendium, Complete Adventurer, Complete Arcane, Complete Divine, Complete Warrior, Monster Manual - Core Rulebook III v.3.5, Dungeon Master's Guide - Core Rulebook II v.3.5, Player's Handbook - Core Rulebook I v.3.5]]
java.lang.NullPointerException
	at pcgen.gui2.tabs.summary.InfoPaneHandler.registerListeners(InfoPaneHandler.java:97)
	at pcgen.gui2.tabs.summary.InfoPaneHandler.<init>(InfoPaneHandler.java:59)
	at pcgen.gui2.tabs.SummaryInfoTab.createModels(SummaryInfoTab.java:658)
	at pcgen.gui2.tabs.InfoTabbedPane.setCharacter(InfoTabbedPane.java:156)
	at pcgen.gui2.CharacterTabs.stateChanged(CharacterTabs.java:136)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:418)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:269)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:143)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:74)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(JTabbedPane.java:622)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(JTabbedPane.java:597)
	at java.desktop/javax.swing.JTabbedPane.insertTab(JTabbedPane.java:737)
	at java.desktop/javax.swing.JTabbedPane.addTab(JTabbedPane.java:804)
	at pcgen.gui2.util.SharedTabPane.addTab(SharedTabPane.java:73)
	at pcgen.gui2.CharacterTabs.addCharacter(CharacterTabs.java:109)
	at pcgen.gui2.CharacterTabs.elementAdded(CharacterTabs.java:147)
	at pcgen.facade.util.AbstractListFacade.fireElementAdded(AbstractListFacade.java:113)
	at pcgen.facade.util.DefaultListFacade.addElement(DefaultListFacade.java:106)
	at pcgen.facade.util.DefaultListFacade.addElement(DefaultListFacade.java:100)
	at pcgen.system.CharacterManager.createNewCharacter(CharacterManager.java:99)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1086)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1075)
	at pcgen.gui2.PCGenActionMap$NewAction.actionPerformed(PCGenActionMap.java:519)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by BahamutDragon** [comment]
Hi Mate,

6.08 version of PCGen should use the 6.08 branch. Master branch is for the latest version of PCGen development, today that is the 6.09.xx development series.

**Comment by tivv** [comment]
Yes, I can confirm, works with 6.09! Thanks!
