### ISSUE TITLE
Failed to Load Campaigns for True20

### ISSUE THREAD

**Issue by warp-darmatter** [BahamutDragon/pcgen#1077]
22:10:38.214 INFO main Main:138 Starting PCGen v6.08.00 RC8
22:10:47.70 INFO main LanguageBundle:134 Initialising language bundle with locale en.
22:10:50.594 SEVERE main LookAndFeelManager:222 Look and Feel Java cannot be found
22:19:52.844 INFO Thread-2 SourceFileLoader:534 Loading game True20 and sources [Green Ronin - True20 Adventure Roleplaying Revised, True Sorcery].
22:19:53.660 LSTERROR Thread-2 LstObjectFileLoader:586 file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_skills.lst (13): PObject Spellcraft not found; .MOD skipped.
22:19:54.228 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Command
22:19:54.229 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.230 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Craft (Stoneworking)
22:19:54.230 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.231 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Decipher Script
22:19:54.231 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_classes.lst in tokens: [plugin.lsttokens.pcclass.CskillToken]
22:19:54.231 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.232 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Heal
22:19:54.232 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.233 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Hide
22:19:54.233 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.233 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Knowledge (Arcana)
22:19:54.234 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.234 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Knowledge (Nature)
22:19:54.234 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.235 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Knowledge (Planes)
22:19:54.235 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.235 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Move Silently
22:19:54.236 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.236 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Open Locks
22:19:54.237 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.237 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Speak Language
22:19:54.237 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_classes.lst in tokens: [plugin.lsttokens.pcclass.CskillToken]
22:19:54.238 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Spellcraft
22:19:54.238 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_classes.lst in tokens: [plugin.lsttokens.pcclass.CskillToken]
22:19:54.239 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.239 SEVERE Thread-2 CDOMFactory:105 Unconstructed Reference: Skill Spot
22:19:54.239 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.243 SEVERE Thread-2 AbstractReferenceManufacturer:294 Error: No Skill objects of TYPE=Craft were loaded but were referred to in the data
22:19:54.246 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
22:19:54.246 SEVERE Thread-2 AbstractReferenceManufacturer:294 Error: No Skill objects of TYPE=Knowledge were loaded but were referred to in the data
22:19:54.247 SEVERE Thread-2 TrackingReferenceContext:102   Was used in file:/home/gdale/pcgen/homebrewdata/data/true20/green_ronin/true_sorcery/ts_classes.lst in tokens: [plugin.lsttokens.pcclass.CskillToken]
22:19:54.250 SEVERE Thread-2 AbilityCategory:694 Unconstructed Reference: Ability Category Special Ability All Automatic Proficiencies
22:19:54.252 SEVERE Thread-2 AbilityCategory:694 Unconstructed Reference: Ability Category FEAT Simple Weapon Proficiency
22:19:54.288 SEVERE Thread-2 SourceFileLoader:526 Exception loading files.
java.lang.IllegalStateException: Cannot ask for contained objects: Reference has not been resolved
	at pcgen.cdom.reference.CDOMTypeRef.getContainedObjects(CDOMTypeRef.java:216)
	at plugin.lsttokens.pcclass.CskillToken.process(CskillToken.java:200)
	at plugin.lsttokens.pcclass.CskillToken.process(CskillToken.java:43)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:278)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:261)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:755)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:495)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:244)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:72)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:40)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by BahamutDragon** [comment]
The set is incomplete. It will be a bit to get the missing items in.

**Comment by warp-darmatter** [comment]
Hi BahamutDragon
Thanks for the update. A pity, I was really looking forward to checking out this particular set. Anyhow I will wait patiently for it to be completed.

**Comment by BahamutDragon** [comment]
Implementing the entire source will be a bit. Was there anything specific you need available now?

**Comment by warp-darmatter** [comment]
Hi
I am not sure I understand what you are asking, could you please explain ?

**Comment by RX4NT9UP** [comment]
I also recently tried to use this module. Let me know if I can help at all, I have a tiny bit of experience with pcgen files and I own a complete set of true20 sourcebooks.

**Comment by BahamutDragon** [comment]
Sorry for the massive delays. This might be stable enough to start playing with. Lots left to work on.

**Comment by warp-darmatter** [comment]
Thanks BahamutDragon, I will download and let you know.
