### ISSUE TITLE
Can't load XGE

### ISSUE THREAD

**Issue by omegasome** [BahamutDragon/pcgen#1122]
PCGen v 6.07.06 (the only version I can find) works fine when I use Dungeons & Dragons 5e - Core Books, but when I try to load XGE from master, it throws an error "Failed to load campaigns, see log for more details."

The log outputs:

```04:17:32.142 INFO Thread-10 SourceFileLoader:555 Loading game 5e and sources [Dungeons & Dragons 5e - Core Books, Xanathar's Guide To Everything].
04:17:32.147 LSTERROR Thread-10 CDOMControlLoader:153 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/C:/Users/natha/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst )
04:17:32.147 LSTERROR Thread-10 CDOMControlLoader:153 Illegal Token 'DEFAULTVARIABLEVALUE' 'HANDED|Right' for pcgen.cdom.content.DefaultVarValue HANDED Right in file:/C:/Users/natha/AppData/Local/PCGen/6.07.06/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
04:17:32.150 SEVERE Thread-10 SourceFileLoader:545 Exception loading files.
java.lang.IllegalArgumentException: FactKey: BaseSize does not store objects of pcgen.core.SizeAdjustment
	at pcgen.cdom.enumeration.FactKey.getConstant(FactKey.java:96)
	at pcgen.cdom.content.fact.FactDefinition.getFactKey(FactDefinition.java:125)
	at pcgen.cdom.content.fact.FactDefinition.activateKey(FactDefinition.java:61)
	at pcgen.cdom.content.ContentDefinition.activate(ContentDefinition.java:274)
	at pcgen.persistence.SourceFileLoader.processFactDefinitions(SourceFileLoader.java:744)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:588)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:502)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:243)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Thread.java:748)
```

It may be a version issue, but this is the only version I can find, and there doesn't appear to be a branch targeting v 6.07.06

**Comment by jagbear** [comment]
The following is from the download page on pcgen.org :
Current stable version is 6.08.00RC8
<https://github.com/PCGen/pcgen/releases/tag/6.08.00RC8>, released
2019-12-25:

You can use the 6.08 branch with this version

**Comment by omegasome** [comment]
Yup, I actually JUST found that on my own. You work fast though.

**Comment by omegasome** [comment]
(strange that the pcgen repo doesn't come up in google or duckduckgo, I was beginning to think it was closed-source software)
