### ISSUE TITLE
[ dnd 3.5 ] Complete divine crashes book loading process

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#370]
After latest master update and PCGen v 6.04.01, loading Complete Divine gets null pointer exception. Reproduces even with simple loading of only Core and Complete Divine

14:20:11.931 SEVERE Thread-38 SourceFileLoader:522 Exception loading files.
java.lang.NullPointerException
	at pcgen.cdom.helper.AbilityTargetSelector.getChoiceClass(AbilityTargetSelector.java:233)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:198)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:50)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:230)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:215)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:651)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:488)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:219)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:54)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:22)
	at pcgen.gui2.util.SwingWorker$2.run(SwingWorker.java:148)
	at java.lang.Thread.run(Unknown Source)

**Comment by BahamutDragon** [comment]
Mate,

You cannot use master branch with older versions of pcgen. Master is the development version, utilizing all the latest updates and pushing improvements. Master should use either the last pcgen development build, or in some cases the latest autobuild to get full use of the features. If you want to use pcgen version 6.04.01 then you must use the branch 6.04.01.

Best,

**Comment by shadowfury** [comment]
Thanks, so what release of these - http://sourceforge.net/projects/pcgen/files/PCGen%20Unstable/ i should use for master branch?

And i assume that all new found bugs would also be fixed for master only, and no new fixes for 6.04.01 , correct?

**Comment by Skarrux156** [comment]
I would download the latest version form the link in the readme friend.
And yes you're correct. All new fixes go toward master.

**Comment by BahamutDragon** [comment]
I use the autobuilds from the development line:
http://www.pcgen.org/autobuilds/download.html (Latest Updates, fixes and features)
Which would give you 6.07.00

If you want the upcoming 6.06.00 instead, the link is:
http://www.pcgen.org/autobuilds-prod/download.html
Which is set to give you the current production version - 6.06.00RC2.

6,04,01 branch update support was discontinued in light of the upcoming 6.06.00 release. Once the development branch diverts from being compatible with 6.06, a new branch for 6.06.00 will be created to house dual support as 6.04.01 had.

You can still use 6.04.01 for the time being, just grab the 6.04.01 branch. Last update was a month ago.

Best.
