### ISSUE TITLE
DnD E5 - Small Creature adding weapon throws error.

### ISSUE THREAD

**Issue by uberdaff** [BahamutDragon/pcgen#403]
Easy to reproduce, create a gnome, try to buy a shortsword.
No problem buying stuff for other races, have tried dwarf, elf, half-elf and human.

**Comment by uberdaff** [comment]
`java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:400)
	at java.util.ArrayList.get(ArrayList.java:413)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1211)
	at pcgen.core.Globals.adjustDamage(Globals.java:827)
	at pcgen.core.Globals.adjustDamage(Globals.java:1497)
	at pcgen.core.Equipment.adjustDamage(Equipment.java:6370)
	at pcgen.core.Equipment.getDamageAdjustedForSize(Equipment.java:6404)
	at pcgen.core.Equipment.resizeItem(Equipment.java:3772)
	at pcgen.gui2.facade.CharacterFacadeImpl.getEquipmentSizedForCharacter(CharacterFacadeImpl.java:3797)
	at pcgen.gui2.tabs.PurchaseInfoTab$AddAction.actionPerformed(PurchaseInfoTab.java:540)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.awt.EventQueue$4.run(EventQueue.java:718)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`

**Comment by uberdaff** [comment]
Has to do with the size of the race it seems. Other races with size:S have the same issue. Changing SIZE to M fixes the issue.

**Comment by BahamutDragon** [comment]
Is this with 6.06.00RC2?

**Comment by BahamutDragon** [comment]
Pull the updated gamemode files, replace the existing gamemode files with those and that should fix the small creature issue.

**Comment by uberdaff** [comment]
Works indeed, thanks for the work your doing, really appreciated!
