### ISSUE TITLE
preview summary points to an invalid file

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#463]
I get this regularly on my output:

```
15:02:03.414 SEVERE html-sheet-thread ExportHandler:272 Error in ExportHandler::write
java.io.FileNotFoundException: preview/summary/35e_info.html (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at pcgen.io.ExportHandler.write(ExportHandler.java:240)
        at pcgen.gui2.facade.CharacterFacadeImpl.export(CharacterFacadeImpl.java:2712)
        at pcgen.gui2.tabs.models.HtmlSheetSupport$DocumentBuilder.call(HtmlSheetSupport.java:198)
        at pcgen.gui2.tabs.models.HtmlSheetSupport$DocumentBuilder.call(HtmlSheetSupport.java:191)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

If I change my gameMode file to point to 35e_info.html.ftl (which exists in pcgen 6.06), then it behaves better.

**Comment by BahamutDragon** [comment]
Fixed
