### ISSUE TITLE
java exception trying to parse ph_abilities.lst line 679

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#488]
```
21:57:44.361 SEVERE Thread-3 LstObjectFileLoader:472 Error parsing file file:/home/dmcbride/rpg/dnd3e/pcgen60600/data/vendordata/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst line 679: SITUATION|Bluff=Humanoid (Human|FavoredEnemyBonusHumanoidHuman reached end of String while attempting to match: )
pcgen.core.utils.ParsingSeparator$GroupingMismatchException: SITUATION|Bluff=Humanoid (Human|FavoredEnemyBonusHumanoidHuman reached end of String while attempting to match: )
        at pcgen.core.utils.ParsingSeparator.next(ParsingSeparator.java:122)
        at pcgen.core.bonus.Bonus.newBonus(Bonus.java:186)
        at plugin.lsttokens.BonusLst.parseToken(BonusLst.java:82)
        at plugin.lsttokens.BonusLst.parseToken(BonusLst.java:46)
        at pcgen.rules.persistence.TokenSupport.processToken(TokenSupport.java:73)
        at pcgen.rules.context.LoadContextInst.processToken(LoadContextInst.java:334)
        at pcgen.persistence.lst.LstUtils.processToken(LstUtils.java:161)
        at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:83)
        at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:47)
        at pcgen.persistence.lst.LstObjectFileLoader.loadLstFile(LstObjectFileLoader.java:451)
        at pcgen.persistence.lst.LstObjectFileLoader.loadLstFiles(LstObjectFileLoader.java:117)
        at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:594)
        at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:471)
        at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:222)
        at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:54)
        at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:22)
        at pcgen.gui2.util.SwingWorker$2.run(SwingWorker.java:148)
        at java.lang.Thread.run(Thread.java:745)
```

All the `Humanoid (Human` entries in this line, `data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst` line 679, are missing the closing parenthesis.

**Comment by BahamutDragon** [comment]
Fixed 
bc494dd344f577d4a4af2a91e356a8e79e38d582
and
c18638cace36805e86b21bfc7566a5ef0122475f
