### ISSUE TITLE
4e output sheets not working

### ISSUE THREAD

**Issue by BahamutDragon** [BahamutDragon/pcgen#548]
I was experimenting with your data sets to use with a 4e campaign. Everything works perfect until I go to print a character sheet.  The character sheet shows up nicely inside of PCGen, but when I go to print the character sheet I get the following error.

 

“Cannot perform the requested operation until all page are rendered. Please wait” and then there is an OK button.  Waiting produces nothing further.

 

If I go to the debug log I see the following:

 

org.apache.fop.fo.ValidationException: "fo:table-row" is missing child elements. Required content model: (table-cell+) (No context info available)

            at org.apache.fop.events.ValidationExceptionFactory.createException(ValidationExceptionFactory.java:38)

            at org.apache.fop.events.EventExceptionManager.throwException(EventExceptionManager.java:54)

            at org.apache.fop.events.DefaultEventBroadcaster$1.invoke(DefaultEventBroadcaster.java:175)

            at com.sun.proxy.$Proxy0.missingChildElement(Unknown Source)

            at org.apache.fop.fo.FONode.missingChildElementError(FONode.java:549)

            at org.apache.fop.fo.flow.table.TableRow.finalizeNode(TableRow.java:115)

            at org.apache.fop.fo.FONode.endOfNode(FONode.java:326)

            at org.apache.fop.fo.flow.table.TableRow.endOfNode(TableRow.java:108)

            at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:349)

            at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:177)

            at org.apache.xml.serializer.ToXMLSAXHandler.endElement(ToXMLSAXHandler.java:263)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1401)

            at org.apache.xalan.templates.ElemForEach.transformSelectedNodes(ElemForEach.java:425)

            at org.apache.xalan.templates.ElemForEach.execute(ElemForEach.java:265)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)

            at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.templates.ElemLiteralResult.execute(ElemLiteralResult.java:1376)

            at org.apache.xalan.templates.ElemApplyTemplates.transformSelectedNodes(ElemApplyTemplates.java:395)

            at org.apache.xalan.templates.ElemApplyTemplates.execute(ElemApplyTemplates.java:178)

            at org.apache.xalan.transformer.TransformerImpl.executeChildTemplates(TransformerImpl.java:2400)

            at org.apache.xalan.transformer.TransformerImpl.applyTemplateToNode(TransformerImpl.java:2270)

            at org.apache.xalan.transformer.TransformerImpl.transformNode(TransformerImpl.java:1356)

            at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:709)

            at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1273)

            at org.apache.xalan.transformer.TransformerImpl.transform(TransformerImpl.java:1251)

            at pcgen.util.fop.FopTask.run(FopTask.java:204)

            at java.lang.Thread.run(Thread.java:745)

 

The version of PCGen I’m using is 6.06.00

Java version: 1.8.0_91-b14

**Comment by BahamutDragon** [comment]
Corrected locally. Sent the updated files to the pcgen maintainers to update their versions.
