### ISSUE TITLE
Feat description is not shown [pcgen 6.07.01]

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#670]
After i picked up latest update of sources feat info failed to load every time and is blank every time. In log this error is shown every time i select feat. It seems like it misses needed info. Perhaps i need to put additional output?

![image](https://cloud.githubusercontent.com/assets/2230015/25275657/1385c4c6-269f-11e7-82a3-41cd91ccce70.png)

**Comment by BahamutDragon** [comment]
I would need the full text of the log. Once PCGen generates a Null Pointer Exception "NPE" all bets are off. What feat did you try to add?

**Comment by shadowfury** [comment]
This was entire log. It happen every time i select any feat (click on it in Feat& Abilities > Feat > Name tab). Nothing is shown in Feat Info window and such error is shown in log.

For a new character that switched to feat tab and clicked on any feat i see following in log:

22:03:23.457 INFO main LanguageBundle:136 Initialising language bundle with locale en_US.
22:03:43.763 INFO Thread-6 SourceFileLoader:560 Loading game 35e and sources [Complete Adventurer, Complete Arcane, Complete Champion, Complete Divine, Complete Mage, Complete Scoundrel, Complete Warrior, Dungeon Master's Guide II, Dungeons & Dragons - Core Books, Expanded Psionics Handbook, Fiendish Codex II, Magic Item Compendium, Miniatures Handbook, Monster Manual II, Monster Manual III, Player's Guide to Faerun, Player's Handbook II, Spell Compendium, Unearthed Arcana (Complete), Races of Destiny].
22:03:58.545 INFO AWT-EventQueue-0 CharacterManager:107 Created new character Unnamed 1.
22:04:07.429 SEVERE AWT-EventQueue-0 Main:581 Uncaught error - ignoring
java.lang.NullPointerException
	at pcgen.gui2.facade.Gui2InfoFactory.appendFacts(Gui2InfoFactory.java:2420)
	at pcgen.gui2.facade.Gui2InfoFactory.getHTMLInfo(Gui2InfoFactory.java:557)
	at pcgen.gui2.tabs.AbilityChooserTab$InfoHandler.valueChanged(AbilityChooserTab.java:445)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by shadowfury** [comment]
I think i know what happened - i noticed this bug a few days ago and it started to reproduce with all source book selection. Another thing that also happen a few days ago - i updated java to latest version (1.8.0_131-b11 (Oracle Corporation)). I think that's why i am punished, not related to sources

**Comment by BahamutDragon** [comment]
I cannot fix a Java release issue. I think this would be best directed to the pcgen team. They have the resources to investigate and correct these problems.

**Comment by shadowfury** [comment]
Yeah, i should have checked java earlier, not first time i've encountered weird behavior due to java version. I wish there was a java version requirement with each pcgen release that is guaranteed to work without issue

**Comment by shadowfury** [comment]
Strange thing is that when i only load this book i get no error on feat clicks:
![image](https://cloud.githubusercontent.com/assets/2230015/25308004/2f60ca54-27b4-11e7-97ff-6c571e3930f5.png)
but when i load a single core book this one

![image](https://cloud.githubusercontent.com/assets/2230015/25308008/41212ac2-27b4-11e7-9938-64e81dd504f4.png)

i get zero info on a feats and null pointer exceptions. As if these core rules book contains some error or i miss some game mode info or something

**Comment by shadowfury** [comment]
Another update - i loaded sources that were on Commits on Mar 20, 2017 - at this commit - 0f72852786538e4281abde62036596d107378936 
And bug error is not present! Trying to narrow it down to find commit that broke things

**Comment by shadowfury** [comment]
I found commit that broke feats info tab and a few other tabs (spell description also i think).
It's this Warforged change - https://github.com/BahamutDragon/pcgen/commit/43635482763ea4479830d9b82deba158874716be

previous commit does not have this behavior

https://github.com/BahamutDragon/pcgen/commit/53fb4d020449757fa098a2c84362a7b5d657ed64

**Comment by BahamutDragon** [comment]
Mate, I loaded the same source, and my feats show just fine.

**Comment by BahamutDragon** [comment]
![image](https://cloud.githubusercontent.com/assets/4307487/25308324/4af0ac56-2766-11e7-9e56-85f132a466c1.png)
I typically test my commits before I upload to verify nothing breaks

**Comment by BahamutDragon** [comment]
The 3.5e sources I support really should be using the Bahamut35e GameMode, as the referenced commit is only supported in my GameMode.

**Comment by shadowfury** [comment]
I again reinstalled pcgen (with java version included with install), downloaded clean latest sources, pasted them to /vendordata, copied gameMode folder, loaded single book in Bahamut 3.5e mode
![image](https://cloud.githubusercontent.com/assets/2230015/25308519/ab0aedba-27be-11e7-8c36-1d4f00e660e6.png)
and still have this issue even in Bahamut mode
![image](https://cloud.githubusercontent.com/assets/2230015/25308522/ba58b874-27be-11e7-9ffd-e3df2563ff6b.png)
I have no idea what am i missing

 and even if i figure out how to make it work, it looks like i'll need to redo all characters i made for 3.5 from scratch, as they had different game mode. Is there a way to make that single change to be loaded only when in Bahamut mode?

**Comment by BahamutDragon** [comment]
Simple edit made to the character file can make an existing character work. I would not worry about it though. The edit is for making the Warforged characters work correctly. No other major deviations between my gamemode and the pcgen supplied version. Other than it will help you avoid loading books not fully supported.

I am not running the latest java version like you, which sounds like a likely suspect. I will upgrade my java and see if that impacts anything on my end.

**Comment by shadowfury** [comment]
I assume it means changing line GAMEMODE:35e in character file. Thanks for pointing out!

About java - i uninstalled my system java and instead downloaded this release of pcgen - https://sourceforge.net/projects/pcgen/files/PCGen%20Unstable/6.07.01/

it comes already with java within pcgen folder - pcgen-6.07.01-full.zip.

I checked and it uses java version "1.8.0_66" which is presumable desired version for pcgen as it is packed with it.  Though it works correctly with sources previous to warforged commits. If java was issue it would have probably failed in both versions of sources

**Comment by BahamutDragon** [comment]
I do not know the full ins and outs of what the pcgen team does. You can reach out to them direct. They have a live chat that frequently has their team in it. Reach out and ask them, they may have further. This is the link they always promote: https://www.hipchat.com/gzYdCc3Vn

**Comment by shadowfury** [comment]
As a temporary solution i had to revert those two commits in my fork, hopefully this is only my issue and when 6.08.01 is released i'll just grab correct version. Meanwhile, interesting merges for me ahead :) Sorry for taking your time mate and thanks for help!
