### ISSUE TITLE
Issue Loading 3.5e Bahamut books

### ISSUE THREAD

**Issue by AVellucci** [BahamutDragon/pcgen#747]
I know I should probably wait for an official release before reporting this, in case it's just an alpha version issue, but it look like PCGen has changed a bit and it may cause issues later if not addressed before the next dev or official release. **Version used was 6.0.7.04**

When trying to load the Bahamut "Dungeons & Dragons - Core Books" Basic sources option. which contains just the 3.5e Core Book I get an error which doesn't allow my campaign or character sheets to load.

I've supplied the Error Log from PCGen, maybe I'm doing something wrong, but from what I might interpret, it seems PCGen has changed something which now requires a value that is not present in the core book.

```
13:35:12.542 INFO Thread-14 SourceFileLoader:555 Loading game 35e and sources [Dungeons & Dragons - Core Books].
13:35:20.293 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment C
13:35:20.295 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.295 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.296 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.296 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.297 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.BonusLst]
13:35:20.297 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.AnyPCToken]
13:35:20.298 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.298 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment D
13:35:20.299 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.299 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.300 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.300 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?]
13:35:20.301 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.DescLst]
13:35:20.302 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.302 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment F
13:35:20.303 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.303 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.304 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?]
13:35:20.304 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst]
13:35:20.305 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.AnyPCToken]
13:35:20.305 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment G
13:35:20.306 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.306 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
13:35:20.307 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_kits.lst in tokens: [plugin.lsttokens.kit.gear.SizeToken]
13:35:20.307 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.308 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.308 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.309 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.BonusLst]
13:35:20.310 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.311 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment H
13:35:20.311 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.312 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.312 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.312 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.313 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.313 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_feats.lst in tokens: [?]
13:35:20.314 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.BonusLst]
13:35:20.314 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
13:35:20.314 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.315 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
13:35:20.315 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment L
13:35:20.316 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.316 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.316 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
13:35:20.317 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.317 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.317 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.318 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_feats.lst in tokens: [?]
13:35:20.318 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_templates.lst in tokens: [?]
13:35:20.319 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.BonusLst]
13:35:20.320 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
13:35:20.322 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.323 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
13:35:20.324 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment M
13:35:20.324 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.325 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
13:35:20.325 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_kits.lst in tokens: [plugin.lsttokens.kit.gear.SizeToken]
13:35:20.329 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst, plugin.lsttokens.CompanionListLst]
13:35:20.329 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.330 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.331 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_templates.lst in tokens: [?]
13:35:20.331 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.BonusLst]
13:35:20.331 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
13:35:20.332 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
13:35:20.332 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.334 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment S
13:35:20.336 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.337 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.337 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_kits.lst in tokens: [plugin.lsttokens.kit.gear.SizeToken]
13:35:20.337 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst, plugin.lsttokens.CompanionListLst]
13:35:20.338 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.338 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.339 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/dungeon_masters_guide/dmg_templates.lst in tokens: [?]
13:35:20.339 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.BonusLst]
13:35:20.339 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
13:35:20.340 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.341 SEVERE Thread-14 CDOMFactory:118 Unconstructed Reference: SizeAdjustment T
13:35:20.341 SEVERE Thread-14 TrackingReferenceContext:119   Was used in null in tokens: [?]
13:35:20.341 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.342 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
13:35:20.342 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
13:35:20.342 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_templates.lst in tokens: [?, plugin.lsttokens.BonusLst]
13:35:20.343 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [?, plugin.lsttokens.AbilityLst, plugin.lsttokens.DescLst]
13:35:20.343 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/players_handbook/ph_spells.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
13:35:20.343 SEVERE Thread-14 TrackingReferenceContext:119   Was used in file:/C:/PCGen/Bahamut/data/35e/wizards_of_the_coast/core/monster_manual/mm_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
13:35:20.823 SEVERE Thread-14 IsdefaultsizeToken:81 Did not find a default size
13:35:20.824 LSTWARN Thread-14 SizeNumToken:106 SizeAdjustment items must have a SIZENUM
13:35:21.570 SEVERE Thread-14 SourceFileLoader:545 Exception loading files.
java.lang.NullPointerException
	at pcgen.cdom.reference.CDOMDirectSingleRef.<init>(CDOMDirectSingleRef.java:60)
	at pcgen.cdom.reference.CDOMDirectSingleRef.getRef(CDOMDirectSingleRef.java:198)
	at pcgen.cdom.enumeration.FormulaKey$1.getDefault(FormulaKey.java:91)
	at pcgen.cdom.base.CDOMObject.getSafe(CDOMObject.java:209)
	at plugin.lsttokens.NaturalattacksLst.process(NaturalattacksLst.java:420)
	at plugin.lsttokens.NaturalattacksLst.process(NaturalattacksLst.java:62)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:264)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:246)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:768)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:507)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:243)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by BahamutDragon** [comment]
Good catch mate. 

Looks like the pcgen team changed where sizes are located. Tested this patch, should fix the problem on your end.

Best,
