### ISSUE TITLE
Failed to load campaign, see log for more details. (PcGen 6.07.07)

### ISSUE THREAD

**Issue by Slexom** [BahamutDragon/pcgen#788]
On PcGen 6.07.07

```

12:02:28.212 INFO Thread-14 SourceFileLoader:565 Loading game Bahamut35e and sources [Dungeons & Dragons - Core Books, Faiths and Pantheons, Arms and Equipment Guide, Book of Exalted Deeds, Complete Adventurer, Complete Arcane, Complete Champion, Complete Divine, Complete Mage, Complete Warrior, Drow of the Underdark, Dungeon Master's Guide II, Expanded Psionics Handbook, Fiend Folio, Fiendish Codex II, Player's Guide to Faerun, Races of Faerun, Shining South, Underdark, Frostburn, Heroes of Horror, Libris Mortis: The Book of the Dead, Lords of Madness, Magic Item Compendium, Magic of Incarnum, Miniatures Handbook, Monster Manual II, Monster Manual III, Player's Handbook II, Sandstorm, Savage Species, Spellbook Archive, Spell Compendium, Stormwrack, The Mind's Eye, Tome of Battle: The Book of Nine Swords, Tome of Magic, Unearthed Arcana (Complete), Weapons of Legacy, Book of Vile Darkness, Cityscape: An Essential Guide to Urban Adventuring, Complete Psionic, Complete Scoundrel, Draconomicon, Dragon Magic, Dungeonscape, Epic Level Handbook, Fey Feature, Champions of Ruin, City of Splendors: Waterdeep, Dragons of Faerun - Web Enhancement - City of Wyrmshadows, Lost Empires of Faerun, Magic of Faerun, Unapproachable East, Champions of Valor, Races of Destiny, Races of Stone, Races of the Dragon, Races of the Wild, Dragon Compendium, Vol 1].
12:02:33.446 SEVERE Thread-14 LstObjectFileLoader:454 Errore durante il parsing del file file:/C:/Users/XXXXXXX/Desktop/pcgen/homebrewdata/pcgen/data/35e/wizards_of_the_coast/supplement/lords_of_madness/lom_abilities.lst linea 191: null
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source)
	at pcgen.rules.context.RuntimeReferenceContext.getManufacturerId(RuntimeReferenceContext.java:74)
	at pcgen.rules.context.AbstractReferenceContext.importObject(AbstractReferenceContext.java:236)
	at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:111)
	at pcgen.persistence.lst.AbilityLoader.parseLine(AbilityLoader.java:36)
	at pcgen.persistence.lst.LstObjectFileLoader.loadLstFile(LstObjectFileLoader.java:433)
	at pcgen.persistence.lst.LstObjectFileLoader.loadLstFiles(LstObjectFileLoader.java:107)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:668)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:512)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:253)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Unknown Source)

12:02:33.447 SEVERE Thread-14 LstObjectFileLoader:456 Errors.LstFileLoader.Ignoring: null not defined.
12:03:43.32 SEVERE Thread-14 SourceFileLoader:555 Exception loading files.
java.lang.IllegalArgumentException: Cannot create Solver of format ALIGNMENT because no default was provided for that format
	at pcgen.base.solver.SolverFactory.getSolver(SolverFactory.java:152)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:811)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:517)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:253)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Unknown Source)



```

**Comment by Slexom** [comment]
And now it work! Thank you.
