### ISSUE TITLE
Failed to load campaign, see log for more details. (PcGen 6.07.07) [d20_one_piece]

### ISSUE THREAD

**Issue by Vivorio** [BahamutDragon/pcgen#791]
```
18:30:22.959 INFO Thread-8 SourceFileLoader:565 Loading game OnePiece and sources [One Piece d20].
18:30:23.29 LSTERROR Thread-8 LstUtils:166 BENEFIT encountered imbalanced Parenthesis: Drawing and holstering your ranged weapon(s) is now a swift action instead of a move action. When you draw your ranged weapon you may also fire a single shot with a ranged shot penalty of -3 at a target in line of sight. If you are drawing two weapons (dual wielding) then each weapon gets a single shot, though the second takes an additional -3 penalty). (Source: file:/C:/Users/danie/Downloads/PC%20Gen/pcgen-master/pcgen-master/data/d20_one_piece/bad_karma_games/core/op_feats.lst )
18:30:23.29 LSTERROR Thread-8 LstUtils:166 Illegal Token 'BENEFIT' 'Drawing and holstering your ranged weapon(s) is now a swift action instead of a move action. When you draw your ranged weapon you may also fire a single shot with a ranged shot penalty of -3 at a target in line of sight. If you are drawing two weapons (dual wielding) then each weapon gets a single shot, though the second takes an additional -3 penalty).' for pcgen.core.Ability Gunslinger Prestige Class Feat / 1 QUICK DRAW in file:/C:/Users/danie/Downloads/PC%20Gen/pcgen-master/pcgen-master/data/d20_one_piece/bad_karma_games/core/op_feats.lst
18:30:23.296 SEVERE Thread-8 SourceFileLoader:555 Exception loading files.
java.lang.IllegalArgumentException: ClassType is not a previously defined FactKey
	at pcgen.cdom.enumeration.FactKey.valueOf(FactKey.java:119)
	at pcgen.core.PCClass.getClassType(PCClass.java:1557)
	at pcgen.core.PCClass.isMonster(PCClass.java:521)
	at pcgen.rules.context.AbstractReferenceContext.buildDerivedObjects(AbstractReferenceContext.java:296)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:797)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:517)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:253)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Unknown Source)


```

**Comment by Vivorio** [comment]
```
16:03:22.69 INFO main Main:140 Starting PCGen v6.07.07
16:03:22.150 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
16:03:42.543 INFO Thread-6 SourceFileLoader:565 Loading game OnePiece and sources [One Piece d20].
16:03:42.997 SEVERE Thread-6 SourceFileLoader:555 Exception loading files.
java.lang.IllegalArgumentException: ClassType is not a previously defined FactKey
	at pcgen.cdom.enumeration.FactKey.valueOf(FactKey.java:119)
	at pcgen.core.PCClass.getClassType(PCClass.java:1557)
	at pcgen.core.PCClass.isMonster(PCClass.java:521)
	at pcgen.rules.context.AbstractReferenceContext.buildDerivedObjects(AbstractReferenceContext.java:296)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:797)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:517)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:253)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by timehm** [comment]
trouble with players hand book

**Comment by BahamutDragon** [comment]
Fixed.

**Comment by tranzmatt** [comment]
I'm still running into this problem:

~/Code/PCGen/pcgen$ ./pcgen.sh 
Available memory: 749084 kB
There is less than 1 GB of free memory available. Will keep default memory limits
min: 256 MB, max: 512 MB
16:39:44.787 INFO main Main:140 Starting PCGen v6.07.08
16:39:45.42 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by pcgen.gui2.tools.Utility (file:/home/mclark/Code/PCGen/pcgen/pcgen.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of pcgen.gui2.tools.Utility
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
16:42:11.266 INFO Thread-2 SourceFileLoader:567 Loading game Modern and sources [Mutants & Masterminds 1e].
16:42:12.197 SEVERE Thread-2 SourceFileLoader:557 Exception loading files.
java.lang.IllegalArgumentException: ClassType is not a previously defined FactKey
	at pcgen.cdom.enumeration.FactKey.valueOf(FactKey.java:121)
	at pcgen.core.PCClass.getClassType(PCClass.java:1557)
	at pcgen.core.PCClass.isMonster(PCClass.java:521)
	at pcgen.rules.context.AbstractReferenceContext.buildDerivedObjects(AbstractReferenceContext.java:296)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:799)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:519)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:255)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by timehm** [comment]
i'm also running into a code similar to this with extracting to
 pdfs
