### ISSUE TITLE
5e players handbook not loading 6.07.06 and up.  6.07.05 works fine with players handbook.

### ISSUE THREAD

**Issue by timehm** [BahamutDragon/pcgen#793]
```
 19:04:33.538 INFO main Main:140 Starting PCGen v6.07.08
19:04:33.922 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
19:05:24.42 LSTERROR main SourcedateLst:83 Error parsing date
java.text.ParseException: Unparseable date: "2016"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at plugin.lsttokens.SourcedateLst.getDate(SourcedateLst.java:79)
	at plugin.lsttokens.SourcedateLst.parseNonEmptyToken(SourcedateLst.java:50)
	at plugin.lsttokens.SourcedateLst.parseNonEmptyToken(SourcedateLst.java:36)
	at pcgen.rules.persistence.token.AbstractNonEmptyToken.parseToken(AbstractNonEmptyToken.java:41)
	at pcgen.rules.persistence.TokenSupport.processClassTokens(TokenSupport.java:140)
	at pcgen.rules.persistence.TokenSupport.processToken(TokenSupport.java:123)
	at pcgen.rules.context.LoadContextInst.processToken(LoadContextInst.java:346)
	at pcgen.rules.context.RuntimeLoadContext.processToken(RuntimeLoadContext.java:20)
	at pcgen.persistence.lst.LstUtils.processToken(LstUtils.java:158)
	at pcgen.persistence.lst.CampaignLoader.parseLine(CampaignLoader.java:193)
	at pcgen.persistence.lst.LstLineFileLoader.loadLstString(LstLineFileLoader.java:102)
	at pcgen.persistence.lst.LstLineFileLoader.loadLstFile(LstLineFileLoader.java:74)
	at pcgen.persistence.lst.CampaignLoader.loadCampaignLstFile(CampaignLoader.java:162)
	at pcgen.persistence.CampaignFileLoader.loadCampaigns(CampaignFileLoader.java:123)
	at pcgen.persistence.CampaignFileLoader.execute(CampaignFileLoader.java:77)
	at pcgen.system.PCGenTaskExecutor.execute(PCGenTaskExecutor.java:48)
	at pcgen.system.Main.startupWithGUI(Main.java:252)
	at pcgen.system.Main.main(Main.java:161)
```
![image](https://user-images.githubusercontent.com/16659685/38761325-b9b706ec-3f4f-11e8-94a3-014142b8b6bf.png)

**Comment by BahamutDragon** [comment]
Mate, I cannot reproduce. Which books are you loading?

**Comment by timehm** [comment]
only players handbook

**Comment by timehm** [comment]
the players handbook from this doesnt work with 6.07.08, 6.07.06. 
![image](https://user-images.githubusercontent.com/16659685/38772901-62b0efb4-400f-11e8-98dc-8de9d3891b27.png)
![image](https://user-images.githubusercontent.com/16659685/38772904-6fb7fa04-400f-11e8-90ed-2f3555b23d76.png)
18:08:47.854 INFO main Main:140 Starting PCGen v6.07.08
18:08:48.536 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
18:10:36.220 LSTERROR main SourcedateLst:83 Error parsing date
java.text.ParseException: Unparseable date: "2016"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at plugin.lsttokens.SourcedateLst.getDate(SourcedateLst.java:79)
	at plugin.lsttokens.SourcedateLst.parseNonEmptyToken(SourcedateLst.java:50)
	at plugin.lsttokens.SourcedateLst.parseNonEmptyToken(SourcedateLst.java:36)
	at pcgen.rules.persistence.token.AbstractNonEmptyToken.parseToken(AbstractNonEmptyToken.java:41)
	at pcgen.rules.persistence.TokenSupport.processClassTokens(TokenSupport.java:140)
	at pcgen.rules.persistence.TokenSupport.processToken(TokenSupport.java:123)
	at pcgen.rules.context.LoadContextInst.processToken(LoadContextInst.java:346)
	at pcgen.rules.context.RuntimeLoadContext.processToken(RuntimeLoadContext.java:20)
	at pcgen.persistence.lst.LstUtils.processToken(LstUtils.java:158)
	at pcgen.persistence.lst.CampaignLoader.parseLine(CampaignLoader.java:193)
	at pcgen.persistence.lst.LstLineFileLoader.loadLstString(LstLineFileLoader.java:102)
	at pcgen.persistence.lst.LstLineFileLoader.loadLstFile(LstLineFileLoader.java:74)
	at pcgen.persistence.lst.CampaignLoader.loadCampaignLstFile(CampaignLoader.java:162)
	at pcgen.persistence.CampaignFileLoader.loadCampaigns(CampaignFileLoader.java:123)
	at pcgen.persistence.CampaignFileLoader.execute(CampaignFileLoader.java:77)
	at pcgen.system.PCGenTaskExecutor.execute(PCGenTaskExecutor.java:48)
	at pcgen.system.Main.startupWithGUI(Main.java:252)
	at pcgen.system.Main.main(Main.java:161)

18:10:36.244 LSTERROR main LstUtils:166 Internal error. (Source: file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/pathfinder/paizo/adventure_path/strange_aeons/players_guide/strange_aeons_players_guide.pcc )
18:10:36.244 LSTERROR main LstUtils:166 Failed in parsing typeStr: SOURCEDATE 2016 for pcgen.core.Campaign Strange Aeons Players Guide
18:10:36.244 LSTERROR main LstUtils:166 Illegal Token 'SOURCEDATE' '2016' for pcgen.core.Campaign Strange Aeons Players Guide in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/pathfinder/paizo/adventure_path/strange_aeons/players_guide/strange_aeons_players_guide.pcc
18:10:42.70 SEVERE main Globals:533 Loaded Campaigns with matching names (Feats of Legend: 20 Alcohol Feats) at different Locations: file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/pathfinder/total_party_kill_games/feats_of_legend_20_alcohol_feats/_feats_of_legends_20_alcohol_feats.pcc file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/pathfinder/tpk_games/Feats%20of%20Legend-20%20Alcohol%20Feats/_FoLAF.pcc
18:10:43.41 SEVERE main Globals:533 Loaded Campaigns with matching names (LPJ9304 Infinite Space Themes The Outlaw Crew) at different Locations: file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/starfinder/lpj_design/infinite_space/themes/LPJ9304_IS_Theme_Outlaw_Crew/_lpj9304.pcc file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/starfinder/lpj_design/infinite_space/themes/theme_outlaw_crew/_lpj9304.pcc
18:10:43.622 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/pathfinder/tpk_games/Feats%20of%20Legend-20%20Alcohol%20Feats/_FoLAF.pcc lists GAMEMODE:Pathfinder_RPG multiple times.
18:10:43.622 SEVERE main FacadeFactory:130 Campaign file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/starfinder/lpj_design/infinite_space/themes/theme_outlaw_crew/_lpj9304.pcc lists GAMEMODE:Starfinder multiple times.
18:12:34.386 INFO Thread-6 SourceFileLoader:567 Loading game 5e and sources [Player's Handbook].
18:12:38.217 SEVERE Thread-6 CDOMFactory:106 Unconstructed Reference: SizeAdjustment G
18:12:38.232 SEVERE Thread-6 TrackingReferenceContext:104   Was used in null in tokens: [?]
18:12:38.232 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
18:12:38.232 SEVERE Thread-6 CDOMFactory:106 Unconstructed Reference: SizeAdjustment H
18:12:38.232 SEVERE Thread-6 TrackingReferenceContext:104   Was used in null in tokens: [?]
18:12:38.232 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
18:12:38.232 SEVERE Thread-6 CDOMFactory:106 Unconstructed Reference: SizeAdjustment L
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in null in tokens: [?]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
18:12:38.248 SEVERE Thread-6 CDOMFactory:106 Unconstructed Reference: SizeAdjustment M
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in null in tokens: [?]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/players_handbook/ph_equipmods.lst in tokens: [plugin.lsttokens.equipmentmodifier.SpropToken]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/players_handbook/ph_equip.lst in tokens: [plugin.lsttokens.equipment.SizeToken]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
18:12:38.248 SEVERE Thread-6 CDOMFactory:106 Unconstructed Reference: SizeAdjustment S
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in null in tokens: [?]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
18:12:38.248 SEVERE Thread-6 CDOMFactory:106 Unconstructed Reference: SizeAdjustment T
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in null in tokens: [?]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/universal_rules/ur_abilities.lst in tokens: [plugin.lsttokens.AbilityLst]
18:12:38.248 SEVERE Thread-6 TrackingReferenceContext:104   Was used in file:/C:/Users/Timeh/AppData/Local/PCGen/6.07.08/data/5e/wizards_of_the_coast/core/players_handbook/ph_races.lst in tokens: [plugin.lsttokens.race.SizeToken]
18:12:38.627 SEVERE Thread-6 IsdefaultsizeToken:81 Did not find a default size
18:12:39.16 SEVERE Thread-6 SourceFileLoader:557 Exception loading files.
java.lang.NullPointerException
	at pcgen.cdom.reference.CDOMDirectSingleRef.<init>(CDOMDirectSingleRef.java:61)
	at pcgen.cdom.reference.CDOMDirectSingleRef.getRef(CDOMDirectSingleRef.java:199)
	at pcgen.cdom.enumeration.FormulaKey$1.getDefault(FormulaKey.java:91)
	at pcgen.cdom.base.CDOMObject.getSafe(CDOMObject.java:217)
	at plugin.lsttokens.NaturalattacksLst.process(NaturalattacksLst.java:391)
	at plugin.lsttokens.NaturalattacksLst.process(NaturalattacksLst.java:61)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:280)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:262)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:806)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:519)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:255)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Thread.java:748)

**Comment by timehm** [comment]
step 1 get pcgen 6.07.06 or .08
step 2 copy and paste  the git hub to the pcgen file, 
step3 try to load player handbook, or core rulebook source 
step 4 gives error mesage that i dont know what to do with

**Comment by timehm** [comment]
User error of github changes didnt change properly when you fixed that issue 23 days ago, figured it out
