### ISSUE TITLE
Unable to create a new character. The error was: null PCGen v6.07.07 [One Piece D20]

### ISSUE THREAD

**Issue by Vivorio** [BahamutDragon/pcgen#794]
When I try to create a character, appear that error, I'm doing something wrong? Right below is the log:

```
02:25:55.619 SEVERE AWT-EventQueue-0 CharacterManager:106 Unable to create character with data DataSet [gameMode=OnePiece, campaigns=[One Piece d20]]
java.lang.NullPointerException
	at pcgen.core.analysis.ChooseActivation.hasNewChooseToken(ChooseActivation.java:40)
	at pcgen.cdom.facet.input.RaceInputFacet.set(RaceInputFacet.java:50)
	at pcgen.core.PlayerCharacter.setRace(PlayerCharacter.java:3489)
	at pcgen.core.PlayerCharacter.<init>(PlayerCharacter.java:600)
	at pcgen.system.CharacterManager.createNewCharacter(CharacterManager.java:94)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1122)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1111)
	at pcgen.gui2.PCGenActionMap$NewAction.actionPerformed(PCGenActionMap.java:552)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


```

**Comment by LegacyKing** [comment]
That looks like a change on our end @BahamutDragon - let me see if I can get Tom to decipher the issue.

**Comment by BahamutDragon** [comment]
New file reference missing. Fixed. 8e5e1007093e3f4838c35dd6c570dfe390d6a78d
