### ISSUE TITLE
Exception loading Mutants and Masterminds into 6.07.08

### ISSUE THREAD

**Issue by tranzmatt** [BahamutDragon/pcgen#807]
When I tried to load Mutants and Masterminds into the latest version of PCGen 6.07.08 (on both Linux and Win 10), I've gotten the following error:

10:32:33.725 INFO main Main:140 Starting PCGen v6.07.08
10:32:33.840 INFO main LanguageBundle:134 Initialising language bundle with locale en_US.
10:33:00.978 INFO Thread-6 SourceFileLoader:567 Loading game Modern and sources [Mutants & Masterminds 1e].
10:33:01.485 SEVERE Thread-6 SourceFileLoader:557 Exception loading files.
java.lang.IllegalArgumentException: ClassType is not a previously defined FactKey
	at pcgen.cdom.enumeration.FactKey.valueOf(FactKey.java:121)
	at pcgen.core.PCClass.getClassType(PCClass.java:1557)
	at pcgen.core.PCClass.isMonster(PCClass.java:521)
	at pcgen.rules.context.AbstractReferenceContext.buildDerivedObjects(AbstractReferenceContext.java:296)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:799)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:519)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:255)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:73)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:41)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.lang.Thread.run(Thread.java:748)

**Comment by BahamutDragon** [comment]
Fixed. 

Be aware it requires a gamemode update.
