### ISSUE TITLE
Failed to load campaigns, see log for details (5e, v6.06.01)

### ISSUE THREAD

**Issue by oa10712** [BahamutDragon/pcgen#809]
Attempting to load 5e sources does not work at all, with any configuration of sources giving the following (or a very similar) error:

```
09:25:52.537 INFO Thread-10 SourceFileLoader:518 Loading game 5e and sources [Player's Handbook, Monster Manual, Dungeon Master's Guide].
09:25:52.538 LSTERROR Thread-10 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:STRING| in file: file:/C:/Users/oa10712/Documents/pcgen/bahamut_sources/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
09:25:52.539 LSTERROR Thread-10 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:BOOLEAN|False in file: file:/C:/Users/oa10712/Documents/pcgen/bahamut_sources/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
09:25:52.539 LSTERROR Thread-10 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:ORDEREDPAIR|0,0 in file: file:/C:/Users/oa10712/Documents/pcgen/bahamut_sources/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
09:25:52.539 LSTERROR Thread-10 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:NUMBER|0 in file: file:/C:/Users/oa10712/Documents/pcgen/bahamut_sources/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
09:25:52.539 LSTERROR Thread-10 CDOMControlLoader:146 Unsure what to do with line with prefix: DEFAULTVARIABLEVALUE.  Line was: DEFAULTVARIABLEVALUE:ALIGNMENT|None in file: file:/C:/Users/oa10712/Documents/pcgen/bahamut_sources/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
09:25:52.540 SEVERE Thread-10 SourceFileLoader:510 Exception loading files.
java.lang.IllegalArgumentException: FactKey: BaseSize does not store objects of pcgen.core.SizeAdjustment
	at pcgen.cdom.enumeration.FactKey.getConstant(FactKey.java:92)
	at pcgen.cdom.content.fact.FactDefinition.getFactKey(FactDefinition.java:134)
	at pcgen.cdom.content.fact.FactDefinition.activateKey(FactDefinition.java:59)
	at pcgen.cdom.content.ContentDefinition.activate(ContentDefinition.java:292)
	at pcgen.persistence.SourceFileLoader.processFactDefinitions(SourceFileLoader.java:665)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:551)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:471)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:222)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:54)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:22)
	at pcgen.gui2.util.SwingWorker$2.run(SwingWorker.java:148)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by BahamutDragon** [comment]
Mate, you have your answer. The master branch is designed for the latest PCGen version available. That is currently 6.07.08. Download that version and you will find these errors go away. 

Best,
