### ISSUE TITLE
Cannot Take First-Level Feat - PCGen v6.06.01

### ISSUE THREAD

**Issue by dialdial** [BahamutDragon/pcgen#893]
Hello.  Thank you for all of your help earlier.  I really do appreciate it.  I do have another question, though.

I am in the process of creating a Whisper Gnome in PCGen; however, I am having difficulty taking the First Level Feat.  I am trying to take either Craven or Dodge; however, when I choose any feat for my first level feat, I receive an error message, which I will include below, along with the associated log.  The feats are listed as black in the Feat Name pane when choosing a first-level feat, and I am able to choose either of them as a third-level feat. I was not able to find any prerequisites online for either of those feats that would conflict with me taking them at first level.  Could you please clarify that for me?  Thank you again for all of your help.

Error Message
Failed to add Ability due to Cannot build CNAbility for Craven/Dodge with incompatible Category: First Level Feat is not compatible with Ability's Category: Feat. See log for further details.

Log
16:08:01.802 SEVERE AWT-EventQueue-0 CharacterAbilities:398 Failed to add ability due to 
java.lang.IllegalArgumentException: Cannot build CNAbility for Craven with incompatible Category: First Level Feat is not compatible with Ability's Category: Feat
	at pcgen.cdom.content.CNAbility.<init>(CNAbility.java:94)
	at pcgen.cdom.content.CNAbilityFactory.getCNAbility(CNAbilityFactory.java:39)
	at pcgen.gui2.facade.CharacterAbilities.addAbility(CharacterAbilities.java:393)
	at pcgen.gui2.facade.CharacterFacadeImpl.addAbility(CharacterFacadeImpl.java:677)
	at pcgen.gui2.tabs.AbilityChooserTab$AddAction.actionPerformed(AbilityChooserTab.java:699)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by BahamutDragon** [comment]
Mate, try again with the more recent 6.08.00 RC4. I am not supporting 6.06 any longer.

**Comment by BahamutDragon** [comment]
Just a very old issue fixed with the recent version.
