### ISSUE TITLE
Alignment D&D 5e

### ISSUE THREAD

**Issue by BarbaAlGhul** [BahamutDragon/pcgen#896]
I'm using PCGen 6.06.01 and source: Dungeons & Dragons 5e - Core Books

Every time I try to put the alignment on a character and save it, next time I load the sheet, the alignment is unselected, it clears my previous selection.

edit: I tried to use PCGen 6.08.00RC4 earlier, but it wasn't loading the sources correctly and it was crashing. What source should I use just to use the core rule books?

**Comment by BarbaAlGhul** [comment]
So, using PCGen 6.08.00RC4, when I try to create a character sheet, this happens:

```
java.lang.NullPointerException
	at pcgen.gui2.tabs.summary.InfoPaneHandler.registerListeners(InfoPaneHandler.java:97)
	at pcgen.gui2.tabs.summary.InfoPaneHandler.<init>(InfoPaneHandler.java:59)
	at pcgen.gui2.tabs.SummaryInfoTab.createModels(SummaryInfoTab.java:658)
	at pcgen.gui2.tabs.InfoTabbedPane.setCharacter(InfoTabbedPane.java:156)
	at pcgen.gui2.CharacterTabs.stateChanged(CharacterTabs.java:136)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(Unknown Source)
	at pcgen.gui2.util.SharedTabPane.addTab(SharedTabPane.java:73)
	at pcgen.gui2.CharacterTabs.addCharacter(CharacterTabs.java:109)
	at pcgen.gui2.CharacterTabs.elementAdded(CharacterTabs.java:147)
	at pcgen.facade.util.AbstractListFacade.fireElementAdded(AbstractListFacade.java:113)
	at pcgen.facade.util.DefaultListFacade.addElement(DefaultListFacade.java:106)
	at pcgen.facade.util.DefaultListFacade.addElement(DefaultListFacade.java:100)
	at pcgen.system.CharacterManager.createNewCharacter(CharacterManager.java:99)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1086)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1075)
	at pcgen.gui2.PCGenActionMap$NewAction.actionPerformed(PCGenActionMap.java:519)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

I'm using Java 64 bits.

**Comment by BahamutDragon** [comment]
Is that using the 6.08 branch or the master repo branch from here?

**Comment by BarbaAlGhul** [comment]
Master repo. But I'm checking right now, could be a problem with my Java version. I downloaded the OpenJDK 11 to use with PCGen but I have Java 8 installed (Android Studio is the reason). I think the program is not using the right jdk right now. (I edited the pcgen.bat to open java passing the jdk 11 folder, but I don't think it's working)

**Comment by BarbaAlGhul** [comment]
So, the problem was really the wrong branch, now it is loading the character sheet without problem and keeping the alignment. Thanks and sorry for the trouble. (and now I can actually know that the openjdk 11 is working too)
