### ISSUE TITLE
3.5e "Failed to load campaigns", fails on mm_kits.lst

### ISSUE THREAD

**Issue by Johnny-Canuck** [BahamutDragon/pcgen#939]
PCGen 6.08.00 RC7 for stability, but this also fails on 6.9.01

I'm using the Bahamut's 3.5e with additional sources selected. On load attempt, I get a "Failed to load campaigns" error, with the following in the log:

```
14:00:46.863 INFO Thread-14 SourceFileLoader:534 Loading game Bahamut35e and sources [Complete Warrior, Heroes of Horror, Expanded Psionics Handbook, Unearthed Arcana (Complete), Tome of Magic, Tome of Battle: The Book of Nine Swords, The Mind's Eye, Stormwrack, Spell Compendium, Spellbook Archive, Sandstorm, Races of Destiny, Races of Eberron, Races of Stone, Complete Adventurer, Complete Arcane, Complete Champion, Complete Divine, Complete Mage, Complete Psionic, Complete Scoundrel, Arms and Equipment Guide, Book of Exalted Deeds, Book of Vile Darkness, Cityscape: An Essential Guide to Urban Adventuring, Draconomicon, Dragon Magic, Drow of the Underdark, Dungeonscape, Deities and Demigods, Epic Level Handbook, Fey Feature, Fiend Folio, Fiendish Codex II, Player's Guide to Faerun, Magic of Faerun, Champions of Valor, Champions of Ruin, Dragons of Faerun - Web Enhancement - City of Wyrmshadows, Faiths and Pantheons, Lost Empires of Faerun, Monster Compendium: Monsters of Faerun, Races of Faerun, Shining South, Unapproachable East, Underdark, Frostburn, Libris Mortis: The Book of the Dead, Lords of Madness, Magic Item Compendium, Magic of Incarnum, Miniatures Handbook, Monster Manual II, Monster Manual III, Races of the Dragon, Races of the Wild, Weapons of Legacy, Dragon Compendium, Vol 1, Dragon Magazine, Dragon Magazine 313, Dragon Magazine 358, City of Splendors: Waterdeep, Heroes of Battle, Dragon Magazine 311, Eberron Campaign Setting, Dungeons & Dragons - Core Books, Dungeon Master's Guide II, Player's Handbook II, Swiftblade, Savage Species].
14:00:46.868 LSTERROR Thread-14 CDOMControlLoader:146 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst )
14:00:46.868 LSTERROR Thread-14 CDOMControlLoader:146 Failed in parsing typeStr: DEFAULTVARIABLEVALUE HANDED|Right for pcgen.cdom.content.DefaultVarValue HANDED Right
14:00:46.868 LSTERROR Thread-14 CDOMControlLoader:146 Illegal Token 'DEFAULTVARIABLEVALUE' 'HANDED|Right' for pcgen.cdom.content.DefaultVarValue HANDED Right in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
14:00:49.262 LSTERROR Thread-14 LstUtils:147 Illegal Token 'LANG' 'AUTO|Common|Loxo' for pcgen.core.Race Loxo in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst
14:00:49.263 LSTERROR Thread-14 LstUtils:147 Illegal Token 'LANG' 'AUTO|Thri-Kreen|Common' for pcgen.core.Race Thri-Kreen (Savage Species) in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst
14:00:49.263 LSTERROR Thread-14 LstUtils:147 Illegal Token 'LANG' 'AUTO|Aquan' for pcgen.core.Race Hippocampus in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst
14:00:49.264 LSTERROR Thread-14 LstUtils:147 Illegal Token 'LANG' 'AUTO|Giant|Common' for pcgen.core.Race Half-Ogre in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst
14:00:49.265 LSTERROR Thread-14 LstUtils:147 Illegal FACT subtoken 'IsPC' 'True' for pcgen.core.Race Anthropomorphic Wolf (Source: file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst )
14:00:49.265 LSTERROR Thread-14 LstUtils:147 Failed in parsing typeStr: FACT IsPC|True for pcgen.core.Race Anthropomorphic Wolf
14:00:49.265 LSTERROR Thread-14 LstUtils:147 Illegal Token 'FACT' 'IsPC|True' for pcgen.core.Race Anthropomorphic Wolf in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst
14:00:53.34 SEVERE Thread-14 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/expanded_psionics_handbook/xph_biosettings.lst: 4 and 2 for Old
14:00:53.34 SEVERE Thread-14 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/expanded_psionics_handbook/xph_biosettings.lst: 5 and 3 for Venerable
14:00:53.36 SEVERE Thread-14 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 0 using the existing 0|Adulthood
14:00:53.36 SEVERE Thread-14 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 1 using the existing 1|Middle Age
14:00:53.36 SEVERE Thread-14 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 2 using the existing 2|Old
14:00:53.37 SEVERE Thread-14 BioSet:634 Found second (non-identical) AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst for Region: None Index: 3 using the existing 3|Venerable
14:00:53.37 SEVERE Thread-14 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst: 2 and 4 for Old
14:00:53.37 SEVERE Thread-14 BioSetLoader:97 Incompatible Index for AGESET in Bio Settings file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/universal_rules/ur_biosettings.lst: 3 and 5 for Venerable
14:00:53.523 SEVERE Thread-14 CDOMFactory:105 Unconstructed Reference: Skill Balace
14:00:53.523 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/savage_species/ss_races.lst in tokens: [plugin.lsttokens.race.MoncskillToken]
14:00:53.524 SEVERE Thread-14 AbstractReferenceManufacturer:294 Error: No Skill objects of TYPE=Craft (Stonemasonry) were loaded but were referred to in the data
14:00:53.524 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/players_handbook/ph_equip.lst in tokens: [plugin.lsttokens.BonusLst]
14:00:53.524 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/players_handbook/ph_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
14:00:53.524 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/monster_manual/mm_abilities.lst in tokens: [plugin.lsttokens.BonusLst]
14:00:53.524 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/core/players_handbook/ph_skills.lst in tokens: [plugin.lsttokens.tempbonus.PCToken]
14:00:53.524 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/wizards_of_the_coast/supplement/epic_level_handbook/el_equip.lst in tokens: [plugin.lsttokens.BonusLst]
14:00:53.528 SEVERE Thread-14 AbstractReferenceManufacturer:294 Error: No WeaponProf objects of TYPE=Martial Ranged were loaded but were referred to in the data
14:00:53.529 SEVERE Thread-14 TrackingReferenceContext:102   Was used in file:/C:/Users/malle/AppData/Local/PCGen/6.08.00RC7/data/homebrew/35e/paizo/dragon_magazine/336/dm336_abilities.lst in tokens: [plugin.lsttokens.auto.WeaponProfToken]
14:00:59.148 SEVERE Thread-14 SourceFileLoader:526 Exception loading files.
java.lang.NullPointerException
	at pcgen.cdom.helper.AbilityTargetSelector.getChoiceClass(AbilityTargetSelector.java:231)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:196)
	at plugin.lsttokens.ChooseLst.process(ChooseLst.java:47)
	at pcgen.rules.context.LoadContextInst.processPostRes(LoadContextInst.java:278)
	at pcgen.rules.context.LoadContextInst.resolvePostDeferredTokens(LoadContextInst.java:261)
	at pcgen.rules.context.RuntimeLoadContext.resolvePostDeferredTokens(RuntimeLoadContext.java:20)
	at pcgen.persistence.SourceFileLoader.finishLoad(SourceFileLoader.java:755)
	at pcgen.persistence.SourceFileLoader.loadCampaigns(SourceFileLoader.java:495)
	at pcgen.persistence.SourceFileLoader.execute(SourceFileLoader.java:244)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:72)
	at pcgen.gui2.util.StatusWorker.construct(StatusWorker.java:40)
	at pcgen.gui2.util.SwingWorker$1.run(SwingWorker.java:160)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by BahamutDragon** [comment]
Pull down the branch corresponding to the pcgen version you are using and try again. The errors should be cleaned up now.

**Comment by BahamutDragon** [comment]
Re-open if the issue still persists.
