### ISSUE TITLE
5e Unearthed Arcana - Revised Ranger not loading (Issue with mixed Sources and wrong data used - needs 6.08 branch)

### ISSUE THREAD

**Issue by Ziechael** [BahamutDragon/pcgen#994]
Apologies if this ends up being a substandard report (new to Github issue tracking!) but when I try to use the Revised Ranger source it breaks PCGen. When I add levels in this class (currently only tested as a secondary class) the summary page becomes unresponsive and popup dialogues are empty until buttons are hovered over, they don't perform the actions anticipated and don't add the levels to the character. Looking at the character sheet tab I can see that they have 'added' there and the xp count goes up accordingly but nothing else changes (or can be confirmed to make the changes I guess).
Please let me know what I can do to help further diagnose any potential issue, either with the data or with my use of it!
Thanks for all the hard work by the way :)

**Comment by BahamutDragon** [comment]
The pcgen.log file helps diagnose the problem. If you can provide that, it would help.

**Comment by Ziechael** [comment]
Haha, yeah, that would have helped... said I was new to this ;)
[pcgen.log](https://github.com/BahamutDragon/pcgen/files/4872269/pcgen.log)

**Comment by Ziechael** [comment]
Figured it might help to just catch what the log captures when attempting to add a single level of Revised Ranger (this is to a level 3 character, multiclass):
```
SEVERE AWT-EventQueue-0 Main:484 Uncaught error - ignoring
java.lang.IllegalStateException: Cannot ask for contains: pcgen.core.Ability Reference Revised Ranger has not been resolved
	at pcgen.cdom.reference.CDOMSimpleSingleRef.getContainedObjects(CDOMSimpleSingleRef.java:237)
	at pcgen.core.PlayerCharacter.processAbilityList(PlayerCharacter.java:8085)
	at pcgen.core.PlayerCharacter.processAbilityListsOnAdd(PlayerCharacter.java:8074)
	at pcgen.core.PlayerCharacter.processAddition(PlayerCharacter.java:9026)
	at pcgen.cdom.facet.ObjectAdditionFacet.dataAdded(ObjectAdditionFacet.java:59)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.add(CDOMObjectConsolidationFacet.java:70)
	at pcgen.cdom.facet.CDOMObjectConsolidationFacet.dataAdded(CDOMObjectConsolidationFacet.java:135)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.CharacterConsolidationFacet.dataAdded(CharacterConsolidationFacet.java:64)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:247)
	at pcgen.cdom.facet.base.AbstractDataFacet.fireDataFacetChangeEvent(AbstractDataFacet.java:194)
	at pcgen.cdom.facet.base.AbstractSourcedListFacet.add(AbstractSourcedListFacet.java:96)
	at pcgen.cdom.facet.ClassLevelChangeFacet.update(ClassLevelChangeFacet.java:64)
	at pcgen.cdom.facet.ClassLevelChangeFacet.levelChanged(ClassLevelChangeFacet.java:89)
	at pcgen.cdom.facet.model.ClassFacet$ClassLevelChangeSupport.fireClassLevelChangeEvent(ClassFacet.java:821)
	at pcgen.cdom.facet.model.ClassFacet.setLevel(ClassFacet.java:330)
	at pcgen.core.PlayerCharacter.setLevelWithoutConsequence(PlayerCharacter.java:8977)
	at pcgen.core.PCClass.addLevel(PCClass.java:852)
	at pcgen.core.PlayerCharacter.incrementClassLevel(PlayerCharacter.java:6849)
	at pcgen.core.PlayerCharacter.incrementClassLevel(PlayerCharacter.java:6748)
	at pcgen.core.PlayerCharacter.incrementClassLevel(PlayerCharacter.java:5421)
	at pcgen.gui2.facade.CharacterFacadeImpl.addCharacterLevels(CharacterFacadeImpl.java:810)
	at pcgen.gui2.tabs.SummaryInfoTab$AddLevelsAction.actionPerformed(SummaryInfoTab.java:1366)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by BahamutDragon** [comment]
Looks like you are loading data from two different locations:
file:/Users/alexthut/Downloads/pcgen/data/spycraft/crafty_games/spycraft/spycraft/spycraft.pcc 
file:/Users/alexthut/Documents/GitHub/pcgen/data/spycraft/crafty_games/spycraft/spycraft/spycraft.pcc

16:11:01.172 INFO Thread-2 SourceFileLoader:534 Loading game 5e and sources [Monster Manual, Player's Handbook, Dragon Knight Class, Blood Hunter Class (Order of the Lycan), Blood Hunter Class (Order of the Venomblooded), Blood Hunter Class, Gunslinger Class, Witch Hunter Class, Monster Manual, Player's Handbook, Dungeon Master's Guide, Adventure - Out of the Abyss, Adventure - Lost Mine of Phandelver, Adventure - Tyranny of Dragons, Xanathar's Guide To Everything, Elemental Evil Player's Companion, Mordenkainen's Tome of Foes, Unearthed Arcana - Races of Eberron, Unearthed Arcana: Feats, Unearthed Arcana - Eberron, Unearthed Arcana - That Old Black Magic, Unearthed Arcana: Revised Ranger, Unearthed Arcana - Artificer, Volo's Guide to Monsters, Sword Coast Adventurer's Guide, Book of Lost Spells].
16:11:01.213 LSTERROR Thread-2 CDOMControlLoader:146 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/Users/alexthut/Documents/GitHub/pcgen/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst )
16:11:01.214 LSTERROR Thread-2 CDOMControlLoader:146 Failed in parsing typeStr: DEFAULTVARIABLEVALUE HANDED|Right for pcgen.cdom.content.DefaultVarValue HANDED Right
16:11:01.214 LSTERROR Thread-2 CDOMControlLoader:146 Illegal Token 'DEFAULTVARIABLEVALUE' 'HANDED|Right' for pcgen.cdom.content.DefaultVarValue HANDED Right in file:/Users/alexthut/Documents/GitHub/pcgen/data/5e/wizards_of_the_coast/core/universal_rules/ur__datacontrols.lst
16:11:01.217 LSTERROR Thread-2 CDOMControlLoader:146 DEFAULTVARIABLEVALUE found an unsupported format: HANDED (Source: file:/Users/alexthut/Documents/GitHub/pcgen/data/4e/wizards_of_the_coast/core/players_handbook/ph__datacontrols.lst )
16:11:01.217 LSTERROR Thread-2 CDOMControlLoader:146 Failed in parsing typeStr: DEFAULTVARIABLEVALUE HANDED|Right for pcgen.cdom.content.DefaultVarValue HANDED Right
16:11:01.217 LSTERROR Thread-2 CDOMControlLoader:146 Illegal Token 'DEFAULTVARIABLEVALUE' 'HANDED|Right' for pcgen.cdom.content.DefaultVarValue HANDED Right in file:/Users/alexthut/Documents/GitHub/pcgen/data/4e/wizards_of_the_coast/core/players_handbook/ph__datacontrols.lst

This all says you are loading MASTER branch data with PCGen 6.08, not 6.09. You need to download 6.08 branch data.

Until you load the correct data with the correct version, everything else becomes suspect.

**Comment by BahamutDragon** [comment]
Closing this as OP has not responded.
