### ISSUE TITLE
4e - "Character Create Failed" "Unable to create new character. The error was: null."

### ISSUE THREAD

**Issue by Hassurunous** [BahamutDragon/pcgen#998]
Tried to follow all of the install steps in the README. Even reinstalled PCGen and tried again. 

Every time I try to make a character in 4e I get this error. Here are the logs. 

Looks like an issue with the Player's Handbook, but I'm not sure how to interpret much more than that.

18:31:33.430 SEVERE AWT-EventQueue-0 CharacterManager:106 Unable to create character with data DataSet [gameMode=4e, campaigns=[Player's Handbook]]
java.lang.NullPointerException
	at pcgen.gui2.tabs.summary.InfoPaneHandler.registerListeners(InfoPaneHandler.java:97)
	at pcgen.gui2.tabs.summary.InfoPaneHandler.<init>(InfoPaneHandler.java:59)
	at pcgen.gui2.tabs.SummaryInfoTab.createModels(SummaryInfoTab.java:658)
	at pcgen.gui2.tabs.InfoTabbedPane.setCharacter(InfoTabbedPane.java:156)
	at pcgen.gui2.CharacterTabs.stateChanged(CharacterTabs.java:136)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.insertTab(Unknown Source)
	at java.desktop/javax.swing.JTabbedPane.addTab(Unknown Source)
	at pcgen.gui2.util.SharedTabPane.addTab(SharedTabPane.java:73)
	at pcgen.gui2.CharacterTabs.addCharacter(CharacterTabs.java:109)
	at pcgen.gui2.CharacterTabs.elementAdded(CharacterTabs.java:147)
	at pcgen.facade.util.AbstractListFacade.fireElementAdded(AbstractListFacade.java:113)
	at pcgen.facade.util.DefaultListFacade.addElement(DefaultListFacade.java:106)
	at pcgen.facade.util.DefaultListFacade.addElement(DefaultListFacade.java:100)
	at pcgen.system.CharacterManager.createNewCharacter(CharacterManager.java:99)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1086)
	at pcgen.gui2.PCGenFrame.createNewCharacter(PCGenFrame.java:1075)
	at pcgen.gui2.PCGenActionMap$NewAction.actionPerformed(PCGenActionMap.java:519)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Hassurunous** [comment]
I get the same error even if I only load the Monster Manual, so it doesn't look like a PHB issue necessarily. Let me know if there's any test I can run for you to help debug.

**Comment by BahamutDragon** [comment]
The master data branch is working fine for me using 6.03-dev from the pcgen team. Are you using a 6.08 version of pcgen with the 6.08 data?

**Comment by BahamutDragon** [comment]
No update from original reporter, closing.

**Comment by Beornwulf** [comment]
I am also getting this issue, with what appears to be the same error

**Comment by FerretDave** [comment]
make sure you have checked out the right branch for your version of pcgen - 'master' is for 6.09.05, while PCGen 6.08.00RC8 needs the 6.08 branch

**Comment by Beornwulf** [comment]
I had missed that, thank you - that now works.
